### PR TITLE
chore: update to LAPIS 0.3.4, SILO 0.2.22

### PR DESCRIPTION
**Pull request by fengelniederhammer**
preview URL: https://lapis034silo0222.loculus.org/

# LAPIS Changelog

### Features

* **lapis:** order CSV/TSV columns of aggregated/details data as specified in the request fields or as in the database config ([6cf8704](https://github.com/GenSpectrum/LAPIS/commit/6cf8704e61c9435b37e3846d210496bcad00a977)), closes [#910](https://github.com/GenSpectrum/LAPIS/issues/910)

### Bug Fixes

* **lapis-docs:** fix link on landing page ([d4137b3](https://github.com/GenSpectrum/LAPIS/commit/d4137b3e3de8daf6a9001f1beaff17ef7d9b53df))

### Features

* **lapis:** abort on startup when silo url has invalid syntax ([373d662](https://github.com/GenSpectrum/LAPIS/commit/373d6625abfb74c46b0ec65f020126c7c87089c4)), closes [#939](https://github.com/GenSpectrum/LAPIS/issues/939)

### Bug Fixes

* **lapis-docs:** Sequence file naming scheme uses indexes now not names ([1e7cd60](https://github.com/GenSpectrum/LAPIS/commit/1e7cd604a3c9ecbd8c5d21e0fa07903ad1aebbe9))

### Features

* **lapis:** add healthcheck to Docker containers ([0944990](https://github.com/GenSpectrum/LAPIS/commit/0944990e1aa97e47bfee43d8356571b23b190c58)), closes [#813](https://github.com/GenSpectrum/LAPIS/issues/813)
* **lapis:** add instance name to landing page json ([6c5f81b](https://github.com/GenSpectrum/LAPIS/commit/6c5f81b1eb445f15813d2166c195331effd5495e))

# SILO Changelog
### Bug Fixes

* correctly escape quotes in field names ([#595](https://github.com/GenSpectrum/LAPIS-SILO/issues/595)) ([7e7b448](https://github.com/GenSpectrum/LAPIS-SILO/commit/7e7b448670c2080bee62c876adb68e6e439e9da6))

### Bug Fixes

* **preprocessing:** resolves spurious OOM crashes when handling large datasets ([6e4eae2](https://github.com/GenSpectrum/LAPIS-SILO/commit/6e4eae283317b932e34008912997bfd6f4037c10))

### Features

* make duckdb memory limit configurable via preprocessing config ([c112eb1](https://github.com/GenSpectrum/LAPIS-SILO/commit/c112eb18976b86240ae23069bf11b7286e634d1f))

### Bug Fixes

* preprocessing: validate that either a ndjson or tsv file was given as input ([#564](https://github.com/GenSpectrum/LAPIS-SILO/issues/564)) ([7bf2ef7](https://github.com/GenSpectrum/LAPIS-SILO/commit/7bf2ef7fafb63fe2938cf846385ddc087290ca3b))

### Features

* do not abort on assertment failures ([4e5f598](https://github.com/GenSpectrum/LAPIS-SILO/commit/4e5f59879ce95c8925e15ca6df2f773d989e5c51))
* panic: add `ASSERT`, `UNREACHABLE`, `UNIMPLEMENTED`, safer env var ([867d08f](https://github.com/GenSpectrum/LAPIS-SILO/commit/867d08f4f8b068617b2102edb1ddb36fa6c585fc))
* update duckdb version ([577c1b2](https://github.com/GenSpectrum/LAPIS-SILO/commit/577c1b29d0dde43caf23227b518b7a1927e1f9be))

### Bug Fixes

* duplicate key in sample.ndjson ([c9b5232](https://github.com/GenSpectrum/LAPIS-SILO/commit/c9b523221a8a1ee20ce8830ce8105f2a248afd13))
* increase duckdb memory limit to 80GB ([20131bb](https://github.com/GenSpectrum/LAPIS-SILO/commit/20131bbd294f1da3683a58e0fb7e58cc72649bd5))
* order of randomized tests changed ([d29b2f2](https://github.com/GenSpectrum/LAPIS-SILO/commit/d29b2f267274db5708e857b22240c782a3fa2e80))

### PR Checklist

~~- [ ] All necessary documentation has been adapted.~~
~~- [ ] The implemented feature is covered by an appropriate test.~~
- [ ] Manual testing:
  - [ ] Let cook on pathoplexus staging to see if all is good before merging here
  - [ ] Integrity check on pathoplexus staging vs prod, using snakemake test pipeline
- [ ] Adjust configs to take advantage of new features
  - [ ] Health checks
  - [ ] TSV column order

### CODE REVIEW

**Comment by corneliusroemer** [comment]
@fengelniederhammer thanks! Is there anything that might break stuff for us? Can't see anything immediately looking at changelog, I assume you would have told us if there was something breaking, but better check explicitly with you :)

**Comment by fengelniederhammer** [comment]
There should be nothing that is relevant for Loculus, except for the "order CSV/TSV columns" feature in LAPIS. 

The changes in SILO were mostly internal stuff or preprocessing issues that we had with large datasets.

**Comment by corneliusroemer** [comment]
Is there anything we could/need to do to take advantage of new features? In particular, from the changelog I'm wondering about the following:

- lapis: add healthcheck to Docker containers ([0944990](https://github.com/GenSpectrum/LAPIS/commit/0944990e1aa97e47bfee43d8356571b23b190c58)), closes https://github.com/GenSpectrum/LAPIS/issues/813
- lapis: order CSV/TSV columns of aggregated/details data as specified in the request fields or as in the database config ([6cf8704](https://github.com/GenSpectrum/LAPIS/commit/6cf8704e61c9435b37e3846d210496bcad00a977)), closes https://github.com/GenSpectrum/LAPIS/issues/910
- make duckdb memory limit configurable via preprocessing config (c112eb1)

Btw, great changelog, well done @fengelniederhammer and @Taepper on this!

**Comment by fengelniederhammer** [comment]
> * lapis: add healthcheck to Docker containers

Loculus could benefit, but AFAIK the LAPIS deployments already have there custom healthchecks implemented in the Helm chart. There would not be significant improvement.



> * make duckdb memory limit configurable via preprocessing config

Given the current size of datasets, this should be pretty much irrelevant. We were having issues because our datasets are in the order of magnitude of 100 GB.

**Review by corneliusroemer — CHANGES_REQUESTED** [review]
Making a blocking review not because of known issues but because we should generally check lapis/silo bumps carefully based on past experience. See checklist in PR description for an idea of what to do.

**Comment by fengelniederhammer** [comment]
How do we move forward on this?
> 
>     * [ ]  Manual testing:
>       
>       * [ ]  Let cook on pathoplexus staging to see if all is good before merging here
>       * [ ]  Integrity check on pathoplexus staging vs prod, using snakemake test pipeline

I don't have access to Pathoplexus deployment infrastructure, someone else would need to deploy and test.
(Also I see quite low risk in updating to these versions as there have been very few changes with quite little impact - of course still good to test.)

>     * [ ]  Adjust configs to take advantage of new features
>       * [ ]  Health checks
I don't see much benefit from implementing the new health check. 
>       * [ ]  TSV column order
That should be it's own feature - implemented in a separate issue.

**Comment by fengelniederhammer** [comment]
What's actually the benefit of testing on Pathoplexus? Why isn't testing on the Loculus preview enough?

**Comment by theosanderson** [comment]
Just that the fields may be in a different order in PP - though on reflection they are probably not! Checking that the order in yaml is the same and testing the loculus preview would also work.

**Comment by theosanderson** [comment]
Had a look at the preview

image

We should probably move accessionVersion to be next to accession and version on pathoplexus alongside merging this. Also the `dataUseTermsUrl` is split apart from the other data use terms.

**Comment by fengelniederhammer** [comment]
I wonder whether we want to move `versionStatus` and `versionComment` next to `version`?

**Review by corneliusroemer — APPROVED** [review]

**Pull request merged**
