### PR TITLE
chore: update SILO to v0.2.17

### PR DESCRIPTION
**Pull request by chaoran-chen**
https://update-silo.loculus.org

### CODE REVIEW

**Review by theosanderson — APPROVED** [review]

**Comment by corneliusroemer** [comment]
In future, preview link would be nice :) and copy of release notes 😀

**Comment by corneliusroemer** [comment]
In future, preview link would be nice :) and copy of release notes 😀

Thorough testing would be good before merge. And documenting the testing that was done here in PR.

@theosanderson what have you tested?

**Comment by theosanderson** [comment]
I have not tested anything apart from the fact that the website comes up so far. All I intend to test is that the number of sequences indicated settles at a reasonable number, which would be an improvement on `main.loculus.org`.

**Comment by theosanderson** [comment]
(I don't propose to roll out to prod today, given prod seems stable)

**Comment by corneliusroemer** [comment]
I ran the awk test script and it passed:

```
curl 'https://lapis.pathoplexus.org/west-nile/sample/unalignedNucleotideSequences?versionStatus=LATEST_VERSION&isRevocation=false&dataUseTerms=OPEN' --silent | grep ">" | awk 'seen[$0]++ {exit 1}'
```

**Review by corneliusroemer — APPROVED** [review]

**Pull request merged**
