### PR TITLE
fix(config): helm default removed

### PR DESCRIPTION
**Pull request by corneliusroemer**
resolves #

preview URL:

### PR Checklist

- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

### CODE REVIEW

**Comment by theosanderson** [comment]
Whether in this PR or elsewhere, could we at some stage disable ENA submission by default? (I just checked Values.yaml and realised we don't)

I realise it's not a real problem as one needs secrets, etc. - but I think default Loculus behaviour should not be (and should not appear to be) to submit to ENA

**Review by anna-parker — APPROVED** [review]

**Comment by corneliusroemer** [comment]
The change here is because somehow helm default seems to not work in our tests - this is a workaround - we're happy to make an issue to change defaults later.

**Comment by anna-parker** [comment]
@theosanderson if its ok as we are currently rolling this out to PP and testing it by default in Loculus is helpful, but yes in a week or so I am very happy to set this to disabled by default!

**Comment by theosanderson** [comment]
There's a way to achieve your desired behaviour now :) I'll make a PR

**Comment by corneliusroemer** [comment]
> There's a way to achieve your desired behaviour now :) I'll make a PR

I'm curious, we just lost quite a few hairs trying to figure the behaviour out. Would have been 1min with cdk8s 🙃

**Comment by theosanderson** [comment]
> I'm curious, we just lost quite a few hairs trying to figure the behaviour out. Would have been 1min with cdk8s 🙃

I think we're probably at cross-purposes, I was just replying to Anna's last message: https://github.com/loculus-project/loculus/pull/2907 (which I know won't be news to you).

**Pull request merged**
