### PR TITLE
chore(ci): Use 2core 'larger' runner, with 75GB disk space

### PR DESCRIPTION
**Pull request by corneliusroemer**
Related to #2752 

Using cheapest "larger" runner that has 2 cores and 75GB storage instead of 14GB storage. This might solve the issue with stalling.

### CODE REVIEW

**Comment by theosanderson** [comment]
Given that E2E failed for this specific run and that the cost implications could be significant I think it would be good to confirm that we are running out of storage before merging this

**Comment by theosanderson** [comment]
It doesn't seem like this is it?: https://github.com/loculus-project/loculus/actions/runs/10793315258

**Comment by corneliusroemer** [comment]
Yeah - not sure, but it wasn't just one run that failed but 3 on main

image

**Comment by corneliusroemer** [comment]
Here it was just timeout due to slower setup, will increase timeout

**Comment by theosanderson** [comment]
My test was running on the current system! I think it's more complicated than it appears - I presume it has 14 GB of storage to use for custom stuff and 50 GB or whatever of baked in standard tools

**Comment by theosanderson** [comment]
I suggest closing this issue. We still have 14 GB "free" with the current set up. Problems on main were possibly some external thing. If they recur we can re-open an issue but it doesn't seem to be about storage.

**Pull request closed without merging**
