### PR TITLE
fix(website): show more helpful error when LAPIS returns error when fetching sequences

### PR DESCRIPTION
**Pull request by fengelniederhammer**
preview URL: https://prettierlapissequenceerro.loculus.org/

### Summary

The message before was not helpful and not pretty either. This is at least helpful (to us), but not very pretty for users either.

### Screenshot

After: 
grafik

Before:
grafik

### PR Checklist

~~- [ ] All necessary documentation has been adapted.~~
~~- [ ] The implemented feature is covered by an appropriate test.~~

### CODE REVIEW

**Review by theosanderson — APPROVED** [review]
Thanks!

**Comment by corneliusroemer** [comment]
Nice, thanks!

**Comment by fengelniederhammer** [comment]
As a side note, because I didn't mention it in the PR header: If it fails to parse the LAPIS error then it will fall back to the old, ugly error. If we also want to prevent that, we can add a generic "Oops, we don't know what went wrong" message there.

**Comment by theosanderson** [comment]
👍 my preference is for potentially informative error messages over totally generic ones (where there aren't security implications)

**Pull request merged**
