### PR TITLE
Keycloak 26

### PR DESCRIPTION
**Pull request by fhennig**
resolves #

preview URL: http://keycloakify-with-kc26.loculus.org

### PR Checklist

- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

### CODE REVIEW

**Comment by fhennig** [comment]
@corneliusroemer I took your changes from this branch https://github.com/loculus-project/loculus/pull/3275 and squashed them and added them on top of https://github.com/loculus-project/loculus/pull/3272 so we can test the keycloakify theme with kc26

**Comment by fhennig** [comment]
tested registering, and also got an email here.

**Comment by chaoran-chen** [comment]
Nice! I tested registration, login, password reset and editing of account information - all worked! (ORCID is the only that that we can't test here, I think)

**Comment by fhennig** [comment]
replaced by: https://github.com/loculus-project/loculus/pull/3304

**Comment by corneliusroemer** [comment]
Sure, you could have just squashed them on top using the PR.

Can you add me properly as a coauthor for those changes using trailing git message annotations?

**Pull request closed without merging**
