### PR TITLE
feat(website): resize images to max-size used in website

### PR DESCRIPTION
**Pull request by corneliusroemer**
Add script `process_images.sh` that allows recompressing in the future if new organisms are added.

Implementing this recommendation from Google's PageSpeedInsights: https://pagespeed.web.dev/analysis/https-pathoplexus-org/gnxkqyl8t4?form_factor=mobile

Brave Browser 2024-09-08 22 47 55

preview URL: https://smaller-images.loculus.org

### PR Checklist

- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

### CODE REVIEW

**Comment by theosanderson** [comment]
Just to warn you - we probably actually need to host the images elsewhere: #2500

**Comment by corneliusroemer** [comment]
#2500 is orthogonal and this PR here won't break anything afaict, let's separate the discussions? Does something prevent you from approving @theosanderson?

**Review by anna-parker — COMMENTED** [review]
Lgtm! I was just wondering how you got calculated the resize as 200x width, I see that we set images as h-32 in tailwind which is (height: 8rem; /* 128px */), so this doesn't fully align with the resulting image sizes. Did you use the mx-auto scaling?

**Review by theosanderson — APPROVED** [review]
Nope, I have no issue with this being merged

**Pull request merged**
