### PR TITLE
preprocessing(specification): Update error schema

### PR DESCRIPTION
**Pull request by theosanderson**
See discussion here: https://loculus.slack.com/archives/C05G172HL6L/p1707326370868269?thread_ts=1707323971.457599&cid=C05G172HL6L

### CODE REVIEW

**Review by corneliusroemer — APPROVED** [review]
I think we can just go with this and adjust during implementation if we find issues.

Field names aren't super important as this is all pretty internal-API stuff, which won't be visible to end users.

**Comment by theosanderson** [comment]
Cornelius Anna and I just discussed and agreed on `unprocessedFields` and `processedFields` and that this is a good idea (though of course anyone is welcome to disagree).

Next task would be to implement it!

**Comment by anna-parker** [comment]
I can try add this later today!

**Comment by anna-parker** [comment]
Closing as this has now been merged in https://github.com/loculus-project/loculus/pull/3348

**Pull request closed without merging**
