### PR TITLE
DO NOT MERGE: Test error schema update on persistent DB

### PR DESCRIPTION
**Pull request by anna-parker**
resolves #

preview URL: https://test-schema-update.loculus.org/

### Steps

- [x] Make DB persistent
- [x] Upload data with errors - stay on review page
- [x] Merge changes from https://github.com/loculus-project/loculus/pull/3348
- [x] Make sure that review page does not crash -> I am logged out of the review page and when I am logged back in the changed have been applied
- [x] After rollout complete increase prepro version 
- [x] Ensure review page is still ok
- [x] potential perform another random db migration to check that db migrations do not overwrite errors next time they are run

### CODE REVIEW

**Comment by anna-parker** [comment]
When updating the preprocessing pipeline version I get another streaming parallelization error: 
```
  File "/opt/conda/lib/python3.12/site-packages/loculus_preprocessing/__main__.py", line 16, in cli_entry
    run(config)
  File "/opt/conda/lib/python3.12/site-packages/loculus_preprocessing/prepro.py", line 811, in run
    etag, unprocessed = fetch_unprocessed_sequences(etag, config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/loculus_preprocessing/backend.py", line 118, in fetch_unprocessed_sequences
    return response.headers["ETag"], parse_ndjson(response.text)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/loculus_preprocessing/backend.py", line 84, in parse_ndjson
    raise Exception(error_msg) from e
Exception: Failed to parse JSON: An unexpected error occurred while streaming, aborting the stream: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO sequence_entries_preprocessed_data (accession, pipeline_version, processing_status, started_processing_at, "version") VALUES (('LOC_000JU6R'), ('2'::int8), ('IN_PROCESSING'), ('2024-12-06 14:03:18.833891+00'), ('1'::int8)) was aborted: ERROR: duplicate key value violates unique constraint "sequence_entries_preprocessed_data_pkey"
```
it looks like when there are two prepro pipelines they might try to process the same sequence at the same time - this leads to duplicate keys

**Comment by theosanderson** [comment]
> it looks like when there are two prepro pipelines they might try to process the same sequence at the same time - this leads to duplicate keys

this shouldn't be true if they have different versions? but maybe there were two of the same version running in parallel?

**Comment by anna-parker** [comment]
> this shouldn't be true if they have different versions? but maybe there were two of the same version running in parallel?

I assumed they were running the same version - but I sadly didn't check - I can try and look at grafana now

**Comment by anna-parker** [comment]
The last "fake" migration has an error because I reused an old view - but I managed to check what I wanted to that the when the migrations are performed again and there are errors/warnings in the correct schema format they are not overwritten: 
image

**Comment by anna-parker** [comment]
@theosanderson this seems to be the case - I just checked in grafana and we had to pods running  in the loculus-preprocessing-west-nile-v2-0 component around that time and the errors show up in both of them.

**Comment by anna-parker** [comment]
Closing to avoid confusing

**Pull request closed without merging**
