### PR TITLE
fix(website): revert hotfix

### PR DESCRIPTION
**Pull request by fengelniederhammer**
preview URL: https://reverthotfix.loculus.org/

### Summary

reverting the commits:
9eed2bc54ee55047d9834c8824c3971485879b48
565cc79f264fed135513f5b8a9281b1389bb39fd
Now that SILO 0.2.16 fixed the issues

### PR Checklist

- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

### CODE REVIEW

**Comment by fengelniederhammer** [comment]
```
09:16:12 ~/Downloads ☕ $ curl 'https://lapis-reverthotfix.loculus.org/cchf/sample/unalignedNucleotideSequences/L?versionStatus=LATEST_VERSION&isRevocation=false&dataUseTerms=OPEN' --silent | grep '>' | wc -l
317
09:16:24 ~/Downloads ☕ $ curl 'https://lapis-reverthotfix.loculus.org/cchf/sample/unalignedNucleotideSequences/L?versionStatus=LATEST_VERSION&isRevocation=false&dataUseTerms=OPEN&length_LFrom=1' --silent | grep '>' | wc -l
726
```

When I download all CCHF L-segment sequences:
* without any special filter, it returns 317 sequences
* with length_LFrom=1 set, it returns 726 sequences
  * that also seems to be correct, because for the same filter /aggregated also shows count: 726.

Logically, it doesn't make sense that LAPIS returns more sequences when we add another filter restriction. The good news seems to be that it's correct as long as we have the hotfix in place, but something is odd - we will investigate.

**Comment by corneliusroemer** [comment]
@fengelniederhammer thanks for investigating! The first curl has duplicates?

Don't count, just look at the lines in your pipeline

**Review by corneliusroemer — CHANGES_REQUESTED** [review]
Some duplicates seem to be there - thanks for opening PR to test!

**Comment by fengelniederhammer** [comment]
After analyzing, the bug is supposedly fixed by https://github.com/GenSpectrum/LAPIS-SILO/pull/552 and unrelated to this change.

**Comment by corneliusroemer** [comment]
What I want to know though: how is it possible that the same issue happened in 3 independent organisms - that all run silo preprocessing independently. If it's stochastic, it should only happen in one instance. Why only in this PR and only now?

**Review by chaoran-chen — APPROVED** [review]
I think that this is now also safe to merge. Thanks! (There is no huge rush to merge this but we also shouldn't wait for too long as this is breaking download for all Loculus instances with multi-segmented genomes that do not have the `length` fields)

**Pull request merged**
